GAME_WIDTH = 800
GAME_HEIGHT = 800

ASTEROID_COUNT = 5
ASTEROID_LARGE_R = 40
ASTEROID_MEDIUM_R = 23
ASTEROID_SMALLISH_R = 13
ASTEROID_SMALL_R = 7
ASTEROID_COLOR = (0, 0, 0)
ASTEROID_BREAK_SPEED_FACTOR = INITIAL_SPEED_FACTOR = 1.25
ADDITIONAL_ASTEROIDS = INITIAL_ADDITIONAL_ASTEROIDS = 2

SPACESHIP_COLOR = (100, 0, 0)
SPACESHIP_HEIGHT = 50
SPACESHIP_RADIUS = 25
SPACESHIP_HEIGHT_OFFSET = 10
SHIP_ACCEL = 5
SHIP_LOOP_OFFSET = SPACESHIP_HEIGHT * 1.15

BULLET_COLOR = (0, 0, 0)
BULLET_RADIUS = 3
BULLET_SPEED = 8
BULLET_FUEL = 450

FPS = 40
BACKGROUND_COLOR = (255, 255, 255)

CRASH_MESSAGE_X = GAME_WIDTH / 3
CRASH_MESSAGE_Y = GAME_HEIGHT / 2

LEVEL_MESSAGE_X, LEVEL_MESSAGE_Y = 10, 3
SCORE_MESSAGE_X, SCORE_MESSAGE_Y = GAME_WIDTH - 150, 3
# self.point_list = [head left back right


